#!/usr/bin/env bash

#
# reis-bootstrap.sh - post-install setup for reis (Razer Blade 16)
# Ubuntu Server 26.04 LTS (Resolute Raccoon), headless, SSH-first.
#


#
# AI Disclosure
#

# Generated by : Claude Fable 5 (Anthropic), model ID claude-fable-5
# Generated on : June 12, 2026
# Reviewed by  : Akil Krishnan (akil.krishnan.slib53@gmail.com)
# Reviewed on  : June 13, 2026


#
# Usage
#

# scp reis-bootstrap.sh reis:
# ssh reis
# sudo bash reis-bootstrap.sh


#
# Notes
#

# Idempotent; safe to re-run. Reboot-and-rerun pattern: if the NVIDIA kernel
# module isn't live after driver install, the script asks for a reboot and
# resumes on the next run. Everything that doesn't need the GPU completes on
# the first pass.

# What it does, in order:
#   1. Pre-bootstrap snapshot - read-only btrfs snapshot
#      /.snapshots/pre-bootstrap-* (first run only); covers / only
#   2. Timezone + base system update - set timezone; apt update +
#      full-upgrade
#   3. Essentials via apt - toolchain, fish, git + git-lfs,
#      btrfs/zfs/partition tooling, driver tooling
#   4. Headless-laptop hardening (lid + sleep) - ignore lid switch; mask
#      sleep/suspend/hibernate
#   5. Wi-Fi via netplan (systemd-networkd) - configure Wi-Fi if WIFI_SSID
#      set; skipped otherwise
#   6. NVIDIA driver (Ubuntu archive - Secure Boot is off, so no MOK steps)
#      - Ubuntu-archive driver via ubuntu-drivers; may exit here asking for
#      a reboot on first run
#   7. CUDA toolkit (Ubuntu 26.04 multiverse - native apt packaging) -
#      cuda-toolkit from multiverse (NVIDIA's own repo has no ubuntu2604
#      yet); patch crt/math_functions.h for glibc noexcept compatibility
#      (LP#2155233)
#   8. NVIDIA container toolkit - archive package, or NVIDIA's
#      distro-agnostic apt repo as fallback
#   9. CUDA smoke test - compile + run a trivial kernel in a temp dir, then
#      remove it
#  10. Homebrew + brew packages - install Homebrew + btop, bat, eza
#  11. fish: default shell, greeting off, aliases, pepper theme
#      (release-blooframe) - chsh to fish; write conf.d (brew + cuda PATH,
#      greeting off, eza aliases); pepper theme (release-blooframe); git-lfs
#      user setup
#  12. Cleanup (caches, installer-persisted secrets, histories) - apt/brew
#      caches; installer secrets in /var/log/installer + /var/lib/cloud;
#      shell histories
#  13. Post-bootstrap snapshot - read-only btrfs snapshot
#      /.snapshots/post-bootstrap-*; covers / only
#  14. ZFS scratch (partition 7, exact 256 GiB - survives reinstalls) -
#      create partition 7 + empty pool ONLY if absent (meant to survive OS
#      reinstalls)
#  15. Record partition table to /boot - binary GPT backup + readable dump;
#      after ZFS so p7 is captured; refreshed each run
#  16. Summary - print versions, pool status, and the secrets-rotation
#      playbook

#
#  Patches & Hacks
#

#   - CUDA Toolkit step patches /usr/local/cuda/.../crt/math_functions.h to
#     add noexcept(true) to rsqrt/rsqrtf, which 26.04's glibc requires.
#     Without it the multiverse cuda-toolkit cannot compile any .cu
#     (Ubuntu bug LP#2155233). Backup at math_functions.h.pre-glibc-patch.
#     Drop the patch block once a corrected toolkit ships.


set -o errexit -o nounset -o pipefail

#
# Configuration
#

# CHANGEME: fill these in.
WIFI_SSID=""                       # "" skips Wi-Fi config (e.g. docked/wired)
WIFI_PSK=""                        # if set: scrub it from your kept copy of
                                   # this script afterwards (see summary)
TIMEZONE="America/Chicago"
BREW_PACKAGES=(btop bat eza)
DISK="/dev/nvme0n1"
ZFS_POOL_NAME="tank"               # empty pool; also used as the GPT partlabel
ZFS_ASHIFT=12                      # 12 = 4 KiB min block (NAND page reality);
                                   # 9 would match the reported 512n geometry.
                                   # Immutable once the pool exists.
ZFS_PART_NUM=7
ZFS_START_SECTOR=1463537664        # exact 256 GiB block per the partition
ZFS_END_SECTOR=2000408575          # table of record (536,870,912 sectors)


#
# Preconditions
#

if [[ ${EUID} -ne 0 ]]; then
  echo "Run with sudo: sudo bash $0" >&2

  exit 1
fi

TARGET_USER="${SUDO_USER:-}"
if [[ -z "${TARGET_USER}" || "${TARGET_USER}" == "root" ]]; then
  echo "Run via sudo from your normal user (not a root shell) so user-level" >&2
  echo "config (fish, theme, Homebrew) lands in the right home." >&2

  exit 1
fi

TARGET_HOME="$(getent passwd "${TARGET_USER}" | cut --delimiter=: --fields=6)"

. /etc/os-release
if [[ "${VERSION_ID:-}" != "26.04" ]]; then
  echo "WARNING: written for Ubuntu 26.04 (found ${PRETTY_NAME:-unknown})." >&2
  echo "         CUDA-from-multiverse below assumes the 26.04 archive." >&2
fi


#
# Helpers
#

step() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

as_user() { sudo --user="${TARGET_USER}" --set-home "$@"; }

snapshot() {  # snapshot <name-prefix>
  # Covers ONLY the btrfs root (/). /boot (ext4), the ESP (FAT32), and the
  # ZFS pool are separate filesystems and are NOT in the snapshot - btrfs
  # cannot snapshot them. A rollback reverts everything on / (apt, Homebrew,
  # fish, driver, CUDA) but leaves /boot's kernel/initramfs as-is, so after a
  # driver install a / rollback can desync initramfs from the rolled-back
  # modules. Moot on a first build; mind it for later rollbacks.
  if [[ "$(findmnt --noheadings --output FSTYPE /)" != "btrfs" ]]; then
    echo "/ is not btrfs - skipping ${1} snapshot" >&2

    return 0
  fi

  mkdir --parents /.snapshots
  btrfs subvolume snapshot -r / "/.snapshots/${1}-$(date +%Y%m%d-%H%M%S)"  # -r (read-only)
}


#
# Steps
#

# Pre-Bootstrap Snapshot

step "Pre-bootstrap snapshot"

shopt -s nullglob
_pre=(/.snapshots/pre-bootstrap-*)
shopt -u nullglob

if [[ ${#_pre[@]} -eq 0 ]]; then
  snapshot pre-bootstrap
else
  echo "pre-bootstrap snapshot already exists (${_pre[0]}) - not duplicating"
fi


# Timezone + Base System Update

step "Timezone + base system update"

timedatectl set-timezone "${TIMEZONE}" || true
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get --yes full-upgrade


# Essentials Via Apt

step "Essentials via apt"

# Same order as the autoinstall packages list: hardware enablement,
# bootstrap dependencies, wants.
apt-get install --yes \
  ubuntu-drivers-common wpasupplicant \
  btrfs-progs curl gdisk parted zfsutils-linux \
  build-essential fish git git-lfs


# Headless-Laptop Hardening

step "Headless-laptop hardening (lid + sleep)"

mkdir --parents /etc/systemd/logind.conf.d
cat > /etc/systemd/logind.conf.d/99-headless-lid.conf <<'EOF'
[Login]
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
EOF
systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target >/dev/null 2>&1 || true
systemctl restart systemd-logind || true
echo "lid-close will not suspend (leave the lid open during long runs - thermals)"


# Wi-Fi

if [[ -n "${WIFI_SSID}" ]]; then
  step "Wi-Fi via netplan (systemd-networkd)"

  WLAN_IF=""
  for _i in /sys/class/net/wl*; do
    [[ -e "${_i}" ]] && WLAN_IF="$(basename "${_i}")" && break
  done

  if [[ -z "${WLAN_IF}" ]]; then
    echo "No wlan interface found - check 'ip link'; skipping Wi-Fi." >&2
  else
    cat > /etc/netplan/60-wifi.yaml <<EOF
network:
  version: 2
  renderer: networkd
  wifis:
    ${WLAN_IF}:
      dhcp4: true
      access-points:
        "${WIFI_SSID}":
          password: "${WIFI_PSK}"
EOF
    chmod 600 /etc/netplan/60-wifi.yaml
    netplan apply
    echo "Wi-Fi configured on ${WLAN_IF} (SSID: ${WIFI_SSID})"
  fi
fi


# NVIDIA Driver

step "NVIDIA driver (Ubuntu archive - Secure Boot is off, so no MOK steps)"

if nvidia-smi >/dev/null 2>&1; then
  echo "driver live: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head --lines=1)"
else
  if ! dpkg --list 2>/dev/null | grep --quiet '^ii  nvidia-driver-'; then
    ubuntu-drivers install
  fi

  if ! nvidia-smi >/dev/null 2>&1; then
    echo
    echo ">>> Driver installed but module not live (normal on first install)."
    echo ">>> Reboot, then re-run this script - it resumes where it left off:"
    echo ">>>   sudo reboot   ->   sudo bash $0"

    exit 0
  fi
fi


# CUDA Toolkit

step "CUDA toolkit (Ubuntu 26.04 multiverse - native apt packaging)"

if command -v nvcc >/dev/null || [[ -x /usr/local/cuda/bin/nvcc ]]; then
  echo "nvcc already present"
else
  apt-get install --yes cuda-toolkit
fi

# glibc-compat patch (Ubuntu bug LP#2155233): the multiverse CUDA toolkit's
# crt/math_functions.h declares rsqrt/rsqrtf without noexcept(true), which
# 26.04's glibc requires - so nvcc cannot compile any .cu until it is fixed.
# Append the specifier when missing; no-op once patched (rerun- and
# package-update-safe), and reverts via the .pre-glibc-patch backup.
# Remove this block once NVIDIA ships a corrected toolkit.
CUDA_MATH_H=/usr/local/cuda/targets/x86_64-linux/include/crt/math_functions.h
if [[ -f "${CUDA_MATH_H}" ]] && grep --quiet --extended-regexp 'rsqrt[ \t]*\([ \t]*double[ \t]+x[ \t]*\)[ \t]*;' "${CUDA_MATH_H}"; then
  cp --no-clobber "${CUDA_MATH_H}" "${CUDA_MATH_H}.pre-glibc-patch"
  sed -i -E \
    -e 's/(\brsqrt[ \t]*\([ \t]*double[ \t]+x[ \t]*\))[ \t]*;/\1 noexcept (true);/' \
    -e 's/(\brsqrtf[ \t]*\([ \t]*float[ \t]+x[ \t]*\))[ \t]*;/\1 noexcept (true);/' \
    "${CUDA_MATH_H}"
  echo "patched ${CUDA_MATH_H} for glibc noexcept compatibility"
else
  echo "CUDA math_functions.h already glibc-compatible or not at expected path - skipping patch"
fi

# Nsight Compute CLI (ncu): packaging on 26.04 may ship it separately.
if ! command -v ncu >/dev/null && ! [[ -x /usr/local/cuda/bin/ncu ]]; then
  apt-get install --yes nsight-compute 2>/dev/null \
    || echo "NOTE: no nsight-compute package found - if 'ncu' is missing after this, install Nsight Compute from NVIDIA's standalone download."
fi

# PATH wiring (bash/sh) only needed if this packaging uses /usr/local/cuda.
# The fish equivalent is written in the Fish section.
if [[ -d /usr/local/cuda/bin ]]; then
  cat > /etc/profile.d/cuda.sh <<'EOF'
if [ -d /usr/local/cuda/bin ]; then
  export PATH="/usr/local/cuda/bin:$PATH"
fi
EOF
fi


# NVIDIA Container Toolkit

step "NVIDIA container toolkit"

if command -v nvidia-ctk >/dev/null; then
  echo "nvidia-container-toolkit already present"
elif apt-cache policy nvidia-container-toolkit 2>/dev/null | grep --quiet 'Candidate: [0-9]'; then
  apt-get install --yes nvidia-container-toolkit            # archive has it
else
  # Fall back to NVIDIA's distro-agnostic apt repo (still apt, just theirs).
  curl --fail --silent --show-error --location \
      https://nvidia.github.io/libnvidia-container/gpgkey \
    | gpg --dearmor --output /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg --yes
  curl --fail --silent --show-error --location \
      https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    | sed --expression='s#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    > /etc/apt/sources.list.d/nvidia-container-toolkit.list
  apt-get update
  apt-get install --yes nvidia-container-toolkit
fi

echo "(when you later install docker/podman: nvidia-ctk runtime configure --runtime=docker)"


# CUDA Smoke Test

step "CUDA smoke test"

NVCC_BIN="$(command -v nvcc || echo /usr/local/cuda/bin/nvcc)"
SMOKE_TMP="$(as_user mktemp --directory)"
as_user tee "${SMOKE_TMP}/hello.cu" >/dev/null <<'EOF'
#include <cstdio>

__global__ void hello() {
    printf("Hello from block %d, thread %d\n", blockIdx.x, threadIdx.x);
}

int main() {
    hello<<<2, 4>>>();
    cudaDeviceSynchronize();
    return 0;
}
EOF
as_user "${NVCC_BIN}" "${SMOKE_TMP}/hello.cu" --output-file "${SMOKE_TMP}/hello"
as_user "${SMOKE_TMP}/hello"
rm --recursive --force "${SMOKE_TMP}"


# Homebrew

step "Homebrew + brew packages (${BREW_PACKAGES[*]})"

BREW_BIN=/home/linuxbrew/.linuxbrew/bin/brew
if [[ ! -x "${BREW_BIN}" ]]; then
  # Pre-create the prefix owned by the user so the installer needs no sudo.
  mkdir --parents /home/linuxbrew/.linuxbrew
  chown --recursive "${TARGET_USER}:" /home/linuxbrew/.linuxbrew
  INSTALL_SH="$(curl --fail --silent --show-error --location \
    https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  as_user env NONINTERACTIVE=1 CI=1 /bin/bash -c "${INSTALL_SH}"
fi

as_user env HOMEBREW_NO_ASK=1 HOMEBREW_NO_ENV_HINTS=1 HOMEBREW_NO_INSTALL_CLEANUP=1 \
  "${BREW_BIN}" install "${BREW_PACKAGES[@]}"


# Fish

step "fish: default shell, greeting off, aliases, pepper theme (release-blooframe)"

FISH_BIN="$(command -v fish)"
if [[ "$(getent passwd "${TARGET_USER}" | cut --delimiter=: --fields=7)" != "${FISH_BIN}" ]]; then
  chsh --shell "${FISH_BIN}" "${TARGET_USER}"
  echo "default shell -> fish (takes effect next login)"
fi

# All conf.d files are written here, before the theme step below invokes fish
# (which autoloads them). Each snippet self-guards on the tool's path, so they
# are safe to write whether or not Homebrew/CUDA landed where expected.
as_user mkdir --parents "${TARGET_HOME}/.config/fish/conf.d"

as_user tee "${TARGET_HOME}/.config/fish/conf.d/brew.fish" >/dev/null <<'EOF'
if test -x /home/linuxbrew/.linuxbrew/bin/brew
    /home/linuxbrew/.linuxbrew/bin/brew shellenv | source
end
EOF

as_user tee "${TARGET_HOME}/.config/fish/conf.d/cuda.fish" >/dev/null <<'EOF'
if test -d /usr/local/cuda/bin
    fish_add_path --global /usr/local/cuda/bin
end
EOF

as_user tee "${TARGET_HOME}/.config/fish/conf.d/reis.fish" >/dev/null <<'EOF'
set --global fish_greeting ''

alias sl eza
alias sla 'eza -la'
alias slr 'eza --tree'
alias slra 'eza -la --tree'
EOF

THEME_REPO="https://github.com/slib53/pepper-fish-theme.git"
THEME_BRANCH="release-blooframe"
THEME_TMP="$(as_user mktemp --directory)"
as_user git clone --branch "${THEME_BRANCH}" --depth 1 "${THEME_REPO}" "${THEME_TMP}/pepper"

# apply_theme.fish copies fish_prompt.fish relative to CWD - run from repo root.
as_user fish --command "cd ${THEME_TMP}/pepper; fish scripts/apply_theme.fish"
rm --recursive --force "${THEME_TMP}"

# Per-user git-lfs setup (filters in ~/.gitconfig).
as_user git lfs install


# Cleanup

step "Cleanup (caches, installer-persisted secrets, histories)"

apt-get autoremove --yes
apt-get clean
as_user "${BREW_BIN}" cleanup --prune=all >/dev/null 2>&1 || true
rm --recursive --force "${TARGET_HOME}/.cache/Homebrew" /root/.cache

# The installer persists the autoinstall YAML - including the LUKS passphrase
# and password hash - into these locations. Remove them.
rm --recursive --force /var/log/installer
cloud-init clean --logs >/dev/null 2>&1 || true   # clears /var/lib/cloud (cached user-data)

# Shell histories (root + user, bash + fish).
rm --force /root/.bash_history "${TARGET_HOME}/.bash_history" \
  /root/.local/share/fish/fish_history \
  "${TARGET_HOME}/.local/share/fish/fish_history"
echo "NOTE: your current login shell rewrites its history on exit -"
echo "      run 'history -c' (bash) or 'history clear' (fish) before logout"
echo "      if you want this session gone as well."


# Post-Bootstrap Snapshot

step "Post-bootstrap snapshot"

snapshot post-bootstrap


# ZFS Scratch

step "ZFS scratch (partition ${ZFS_PART_NUM}, exact 256 GiB - survives reinstalls)"

ZFS_DEV="${DISK}p${ZFS_PART_NUM}"
if [[ -b "${ZFS_DEV}" ]]; then
  _sig="$(blkid --output value --match-tag TYPE "${ZFS_DEV}" 2>/dev/null || true)"
  if [[ "${_sig}" == "zfs_member" ]]; then
    echo "ZFS partition already present - leaving it untouched."
    echo "(import when wanted: zpool import ${ZFS_POOL_NAME}; after an OS"
    echo " reinstall the pool looks foreign, so: zpool import -f ${ZFS_POOL_NAME})"
  else
    echo "WARNING: ${ZFS_DEV} exists but is not zfs_member (TYPE='${_sig:-none}')." >&2
    echo "         Refusing to touch it - resolve by hand." >&2
  fi
else
  sgdisk --new="${ZFS_PART_NUM}:${ZFS_START_SECTOR}:${ZFS_END_SECTOR}" \
         --typecode="${ZFS_PART_NUM}:BF01" \
         --change-name="${ZFS_PART_NUM}:${ZFS_POOL_NAME}" \
         "${DISK}"
  partprobe "${DISK}"
  udevadm settle
  modprobe zfs

  # -o (pool property) - -O (root dataset property)
  zpool create -o ashift="${ZFS_ASHIFT}" -O mountpoint=none \
    "${ZFS_POOL_NAME}" "/dev/disk/by-partlabel/${ZFS_POOL_NAME}"
  zpool export "${ZFS_POOL_NAME}"
  echo "empty pool '${ZFS_POOL_NAME}' created and exported (nothing mounted);"
  echo "import when wanted: zpool import ${ZFS_POOL_NAME}"
fi


# Record Partition Table

step "Record partition table to /boot"

GPT_BAK=/boot/reis-gpt.bak
GPT_TXT=/boot/reis-partition-table.txt

sgdisk --backup="${GPT_BAK}" "${DISK}"

# Human-readable dump: sector-exact, with free-space rows. Header line
# records when and on what it was taken.
{
  echo "# reis partition table - ${DISK}"
  echo "# captured $(date --iso-8601=seconds) by reis-bootstrap.sh"
  echo
  parted --script "${DISK}" unit s print free
} > "${GPT_TXT}"

echo "wrote ${GPT_BAK} (binary, restore: sgdisk --load-backup=${GPT_BAK} ${DISK})"
echo "wrote ${GPT_TXT} (human-readable)"


# Summary

step "Summary"

uname --kernel-release
nvidia-smi --list-gpus 2>/dev/null || true
"${NVCC_BIN}" --version 2>/dev/null | tail --lines=1 || true
zpool list 2>/dev/null || echo "(zpool '${ZFS_POOL_NAME}' exported - import with: zpool import ${ZFS_POOL_NAME})"

echo
echo "Secrets rotation & cleanup - do this at first login:"
echo
echo "  1. Rotate the account password - REQUIRED."
echo "     The seed carried only its SHA-512 hash, never the plaintext - but"
echo "     the hash transited the stick and the installer logs, and hashes"
echo "     crack offline. The install password was a throwaway; burn it now."
echo "       passwd"
echo
echo "  2. Rotate the LUKS passphrase - REQUIRED."
echo "     The install passphrase sat in PLAINTEXT on the stick and in the"
echo "     autoinstall YAML. Rotation is instant and lossless: only the"
echo "     keyslot wrapping the volume key changes - no re-encryption. The"
echo "     console unlock at next boot wants the NEW passphrase."
echo "       sudo cryptsetup luksChangeKey ${DISK}p6"
echo
echo "  3. Wipe the CIDATA stick - RECOMMENDED (tidiness once 1-2 are done)."
echo "     Deleting files or quick-formatting only removes directory entries;"
echo "     the bytes stay recoverable. Overwrite the whole device - identify"
echo "     it carefully first (the wrong device node is destroyed data):"
echo "       lsblk --output NAME,SIZE,MODEL,TRAN"
echo "       sudo shred --verbose --iterations=1 /dev/sdX    # whole stick, not a partition"
echo
echo "  4. Scrub kept copies of the YAML and this script - REQUIRED if"
echo "     WIFI_PSK was set, RECOMMENDED otherwise. Rotation killed the old"
echo "     password and passphrase, but a Wi-Fi PSK stays live until the"
echo "     router changes it. Restore the placeholders before archiving:"
echo "       password: \"CHANGEME-SHA512-CRYPT\""
echo "       key: \"CHANGEME-LUKS-PASSPHRASE\""
echo "       WIFI_PSK=\"\""
echo
echo "  Nothing to rotate for the SSH key - it is public by design. The"
echo "  on-device /etc/netplan/60-wifi.yaml keeps the PSK by operational"
echo "  necessity, root-readable only (mode 600)."
echo
echo "  Partition table recorded to /boot (reis-gpt.bak, reis-partition-table.txt)."
echo "  Copy reis-gpt.bak somewhere OFF this disk - the on-disk copy is no help"
echo "  if the disk is the thing that fails."
echo
echo "  Rollback: this run's snapshots are under /.snapshots (pre-bootstrap-*,"
echo "  post-bootstrap-*). The root can't be replaced while mounted - boot a"
echo "  live/rescue environment, then restore with:"
echo "    btrfs subvolume snapshot /.snapshots/pre-bootstrap-<timestamp> /"
echo
